// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dividends/gauge.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type VestingFrequency int32

const (
	VestingFrequency_VESTING_FREQUENCY_UNSPECIFIED VestingFrequency = 0
	VestingFrequency_VESTING_FREQUENCY_BLOCK       VestingFrequency = 1
	VestingFrequency_VESTING_FREQUENCY_EPOCH       VestingFrequency = 2
)

var VestingFrequency_name = map[int32]string{
	0: "VESTING_FREQUENCY_UNSPECIFIED",
	1: "VESTING_FREQUENCY_BLOCK",
	2: "VESTING_FREQUENCY_EPOCH",
}

var VestingFrequency_value = map[string]int32{
	"VESTING_FREQUENCY_UNSPECIFIED": 0,
	"VESTING_FREQUENCY_BLOCK":       1,
	"VESTING_FREQUENCY_EPOCH":       2,
}

func (x VestingFrequency) String() string {
	return proto.EnumName(VestingFrequency_name, int32(x))
}

func (VestingFrequency) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_904d8195b7413b1f, []int{0}
}

// Params holds parameters for the incentives module
type Params struct {
	// distr_epoch_identifier is what epoch type distribution will be triggered by
	// (day, week, etc.)
	DistrEpochIdentifier string `protobuf:"bytes,1,opt,name=distr_epoch_identifier,json=distrEpochIdentifier,proto3" json:"distr_epoch_identifier,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_904d8195b7413b1f, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetDistrEpochIdentifier() string {
	if m != nil {
		return m.DistrEpochIdentifier
	}
	return ""
}

// Gauge is an object that stores and distributes yields to recipients who
// satisfy certain conditions.
type Gauge struct {
	// id is the unique ID of a gauge
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// address is a bech32-formatted address that holds the tokens to allocate
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// active is a flag to show if the gauge is active
	Active bool `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	// approved_denoms is a list of allowed tokens: only gov can approve tokens
	// that can be used for dividends
	ApprovedDenoms []string `protobuf:"bytes,4,rep,name=approved_denoms,json=approvedDenoms,proto3" json:"approved_denoms,omitempty"`
	// query_condition is *where* the gauge rewards are distributed to
	QueryCondition QueryCondition `protobuf:"bytes,5,opt,name=query_condition,json=queryCondition,proto3" json:"query_condition"`
	// vesting_condition is *how long* the gauge rewards are distributed to
	VestingCondition VestingCondition `protobuf:"bytes,6,opt,name=vesting_condition,json=vestingCondition,proto3" json:"vesting_condition"`
	// vesting_condition is *how frequent* the gauge rewards are distributed to
	VestingFrequency VestingFrequency `protobuf:"varint,7,opt,name=vesting_frequency,json=vestingFrequency,proto3,enum=rollapp.dividends.VestingFrequency" json:"vesting_frequency,omitempty"`
}

func (m *Gauge) Reset()         { *m = Gauge{} }
func (m *Gauge) String() string { return proto.CompactTextString(m) }
func (*Gauge) ProtoMessage()    {}
func (*Gauge) Descriptor() ([]byte, []int) {
	return fileDescriptor_904d8195b7413b1f, []int{1}
}
func (m *Gauge) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Gauge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Gauge.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Gauge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gauge.Merge(m, src)
}
func (m *Gauge) XXX_Size() int {
	return m.Size()
}
func (m *Gauge) XXX_DiscardUnknown() {
	xxx_messageInfo_Gauge.DiscardUnknown(m)
}

var xxx_messageInfo_Gauge proto.InternalMessageInfo

func (m *Gauge) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Gauge) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Gauge) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Gauge) GetApprovedDenoms() []string {
	if m != nil {
		return m.ApprovedDenoms
	}
	return nil
}

func (m *Gauge) GetQueryCondition() QueryCondition {
	if m != nil {
		return m.QueryCondition
	}
	return QueryCondition{}
}

func (m *Gauge) GetVestingCondition() VestingCondition {
	if m != nil {
		return m.VestingCondition
	}
	return VestingCondition{}
}

func (m *Gauge) GetVestingFrequency() VestingFrequency {
	if m != nil {
		return m.VestingFrequency
	}
	return VestingFrequency_VESTING_FREQUENCY_UNSPECIFIED
}

type QueryCondition struct {
	// Types that are valid to be assigned to Condition:
	//	*QueryCondition_Stakers
	Condition isQueryCondition_Condition `protobuf_oneof:"condition"`
}

func (m *QueryCondition) Reset()         { *m = QueryCondition{} }
func (m *QueryCondition) String() string { return proto.CompactTextString(m) }
func (*QueryCondition) ProtoMessage()    {}
func (*QueryCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_904d8195b7413b1f, []int{2}
}
func (m *QueryCondition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCondition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCondition.Merge(m, src)
}
func (m *QueryCondition) XXX_Size() int {
	return m.Size()
}
func (m *QueryCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCondition.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCondition proto.InternalMessageInfo

type isQueryCondition_Condition interface {
	isQueryCondition_Condition()
	MarshalTo([]byte) (int, error)
	Size() int
}

type QueryCondition_Stakers struct {
	Stakers *QueryConditionStakers `protobuf:"bytes,1,opt,name=stakers,proto3,oneof" json:"stakers,omitempty"`
}

func (*QueryCondition_Stakers) isQueryCondition_Condition() {}

func (m *QueryCondition) GetCondition() isQueryCondition_Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *QueryCondition) GetStakers() *QueryConditionStakers {
	if x, ok := m.GetCondition().(*QueryCondition_Stakers); ok {
		return x.Stakers
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*QueryCondition) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*QueryCondition_Stakers)(nil),
	}
}

type VestingCondition struct {
	// Types that are valid to be assigned to Condition:
	//	*VestingCondition_Perpetual
	//	*VestingCondition_Limited
	Condition isVestingCondition_Condition `protobuf_oneof:"condition"`
}

func (m *VestingCondition) Reset()         { *m = VestingCondition{} }
func (m *VestingCondition) String() string { return proto.CompactTextString(m) }
func (*VestingCondition) ProtoMessage()    {}
func (*VestingCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_904d8195b7413b1f, []int{3}
}
func (m *VestingCondition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VestingCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VestingCondition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VestingCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VestingCondition.Merge(m, src)
}
func (m *VestingCondition) XXX_Size() int {
	return m.Size()
}
func (m *VestingCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_VestingCondition.DiscardUnknown(m)
}

var xxx_messageInfo_VestingCondition proto.InternalMessageInfo

type isVestingCondition_Condition interface {
	isVestingCondition_Condition()
	MarshalTo([]byte) (int, error)
	Size() int
}

type VestingCondition_Perpetual struct {
	Perpetual *VestingConditionPerpetual `protobuf:"bytes,1,opt,name=perpetual,proto3,oneof" json:"perpetual,omitempty"`
}
type VestingCondition_Limited struct {
	Limited *VestingConditionLimited `protobuf:"bytes,2,opt,name=limited,proto3,oneof" json:"limited,omitempty"`
}

func (*VestingCondition_Perpetual) isVestingCondition_Condition() {}
func (*VestingCondition_Limited) isVestingCondition_Condition()   {}

func (m *VestingCondition) GetCondition() isVestingCondition_Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *VestingCondition) GetPerpetual() *VestingConditionPerpetual {
	if x, ok := m.GetCondition().(*VestingCondition_Perpetual); ok {
		return x.Perpetual
	}
	return nil
}

func (m *VestingCondition) GetLimited() *VestingConditionLimited {
	if x, ok := m.GetCondition().(*VestingCondition_Limited); ok {
		return x.Limited
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*VestingCondition) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*VestingCondition_Perpetual)(nil),
		(*VestingCondition_Limited)(nil),
	}
}

// QueryConditionStakers queries the stakers
type QueryConditionStakers struct {
}

func (m *QueryConditionStakers) Reset()         { *m = QueryConditionStakers{} }
func (m *QueryConditionStakers) String() string { return proto.CompactTextString(m) }
func (*QueryConditionStakers) ProtoMessage()    {}
func (*QueryConditionStakers) Descriptor() ([]byte, []int) {
	return fileDescriptor_904d8195b7413b1f, []int{4}
}
func (m *QueryConditionStakers) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryConditionStakers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryConditionStakers.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryConditionStakers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryConditionStakers.Merge(m, src)
}
func (m *QueryConditionStakers) XXX_Size() int {
	return m.Size()
}
func (m *QueryConditionStakers) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryConditionStakers.DiscardUnknown(m)
}

var xxx_messageInfo_QueryConditionStakers proto.InternalMessageInfo

// VestingConditionPerpetual is a vesting condition that distributes rewards
// infinitely. Perpetual gauges distribute all their tokens at a single time
// and only distribute their tokens again once the gauge is refilled.
//
// Non-perpetual gauges distribute their tokens equally per period while the
// gauge is in the active period. Perpetual gauges distribute all their tokens
// at a single time and only distribute their tokens again once the gauge is
// refilled.
type VestingConditionPerpetual struct {
}

func (m *VestingConditionPerpetual) Reset()         { *m = VestingConditionPerpetual{} }
func (m *VestingConditionPerpetual) String() string { return proto.CompactTextString(m) }
func (*VestingConditionPerpetual) ProtoMessage()    {}
func (*VestingConditionPerpetual) Descriptor() ([]byte, []int) {
	return fileDescriptor_904d8195b7413b1f, []int{5}
}
func (m *VestingConditionPerpetual) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VestingConditionPerpetual) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VestingConditionPerpetual.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VestingConditionPerpetual) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VestingConditionPerpetual.Merge(m, src)
}
func (m *VestingConditionPerpetual) XXX_Size() int {
	return m.Size()
}
func (m *VestingConditionPerpetual) XXX_DiscardUnknown() {
	xxx_messageInfo_VestingConditionPerpetual.DiscardUnknown(m)
}

var xxx_messageInfo_VestingConditionPerpetual proto.InternalMessageInfo

// VestingConditionLimited is a vesting condition that distributes rewards over
// the specified time. Non-perpetual gauges distribute their tokens equally per
// period while the gauge is in the active period.
type VestingConditionLimited struct {
	// num_units is the number of total epochs/blocks distribution will be
	// completed over
	NumUnits int64 `protobuf:"varint,1,opt,name=num_units,json=numUnits,proto3" json:"num_units,omitempty"`
	// filled_epochs is the number of epochs/blocks distribution has been
	// completed on already
	FilledUnits int64 `protobuf:"varint,2,opt,name=filled_units,json=filledUnits,proto3" json:"filled_units,omitempty"`
}

func (m *VestingConditionLimited) Reset()         { *m = VestingConditionLimited{} }
func (m *VestingConditionLimited) String() string { return proto.CompactTextString(m) }
func (*VestingConditionLimited) ProtoMessage()    {}
func (*VestingConditionLimited) Descriptor() ([]byte, []int) {
	return fileDescriptor_904d8195b7413b1f, []int{6}
}
func (m *VestingConditionLimited) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VestingConditionLimited) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VestingConditionLimited.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VestingConditionLimited) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VestingConditionLimited.Merge(m, src)
}
func (m *VestingConditionLimited) XXX_Size() int {
	return m.Size()
}
func (m *VestingConditionLimited) XXX_DiscardUnknown() {
	xxx_messageInfo_VestingConditionLimited.DiscardUnknown(m)
}

var xxx_messageInfo_VestingConditionLimited proto.InternalMessageInfo

func (m *VestingConditionLimited) GetNumUnits() int64 {
	if m != nil {
		return m.NumUnits
	}
	return 0
}

func (m *VestingConditionLimited) GetFilledUnits() int64 {
	if m != nil {
		return m.FilledUnits
	}
	return 0
}

func init() {
	proto.RegisterEnum("rollapp.dividends.VestingFrequency", VestingFrequency_name, VestingFrequency_value)
	proto.RegisterType((*Params)(nil), "rollapp.dividends.Params")
	proto.RegisterType((*Gauge)(nil), "rollapp.dividends.Gauge")
	proto.RegisterType((*QueryCondition)(nil), "rollapp.dividends.QueryCondition")
	proto.RegisterType((*VestingCondition)(nil), "rollapp.dividends.VestingCondition")
	proto.RegisterType((*QueryConditionStakers)(nil), "rollapp.dividends.QueryConditionStakers")
	proto.RegisterType((*VestingConditionPerpetual)(nil), "rollapp.dividends.VestingConditionPerpetual")
	proto.RegisterType((*VestingConditionLimited)(nil), "rollapp.dividends.VestingConditionLimited")
}

func init() { proto.RegisterFile("dividends/gauge.proto", fileDescriptor_904d8195b7413b1f) }

var fileDescriptor_904d8195b7413b1f = []byte{
	// 589 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x4e, 0xdb, 0x4c,
	0x14, 0xb5, 0x0d, 0x24, 0x64, 0xf2, 0x29, 0x84, 0x11, 0x3f, 0xfe, 0x8a, 0xea, 0x06, 0x77, 0x51,
	0x0b, 0xb5, 0x89, 0x44, 0x2b, 0x75, 0xd7, 0x45, 0x82, 0x03, 0x51, 0x11, 0x18, 0x53, 0x90, 0xe8,
	0xc6, 0x32, 0x9e, 0xc1, 0x8c, 0xb0, 0x3d, 0x66, 0x3c, 0x8e, 0x48, 0x9f, 0xa2, 0x2f, 0xd3, 0x77,
	0x60, 0xc9, 0xb2, 0xab, 0xaa, 0x22, 0xfb, 0x3e, 0x43, 0x65, 0x3b, 0x76, 0x9a, 0x10, 0x5a, 0x76,
	0xb9, 0xe7, 0x9c, 0x7b, 0xee, 0xbd, 0x27, 0xd6, 0x80, 0x55, 0x44, 0xfa, 0x04, 0xe1, 0x00, 0x45,
	0x2d, 0xd7, 0x8e, 0x5d, 0xdc, 0x0c, 0x19, 0xe5, 0x14, 0x2e, 0x33, 0xea, 0x79, 0x76, 0x18, 0x36,
	0x0b, 0xfa, 0xd9, 0x8a, 0x4b, 0x5d, 0x9a, 0xb2, 0xad, 0xe4, 0x57, 0x26, 0x54, 0x3f, 0x80, 0x92,
	0x61, 0x33, 0xdb, 0x8f, 0xe0, 0x3b, 0xb0, 0x86, 0x48, 0xc4, 0x99, 0x85, 0x43, 0xea, 0x5c, 0x5a,
	0x49, 0x17, 0x27, 0x17, 0x04, 0x33, 0x59, 0x6c, 0x88, 0x5a, 0xc5, 0x5c, 0x49, 0x59, 0x3d, 0x21,
	0x7b, 0x05, 0xa7, 0xfe, 0x92, 0xc0, 0xc2, 0x6e, 0x32, 0x18, 0xd6, 0x80, 0x44, 0x50, 0xaa, 0x9d,
	0x37, 0x25, 0x82, 0xa0, 0x0c, 0xca, 0x36, 0x42, 0x0c, 0x47, 0x91, 0x2c, 0xa5, 0x06, 0x79, 0x09,
	0xd7, 0x40, 0xc9, 0x76, 0x38, 0xe9, 0x63, 0x79, 0xae, 0x21, 0x6a, 0x8b, 0xe6, 0xa8, 0x82, 0xaf,
	0xc0, 0x92, 0x1d, 0x86, 0x8c, 0xf6, 0x31, 0xb2, 0x10, 0x0e, 0xa8, 0x1f, 0xc9, 0xf3, 0x8d, 0x39,
	0xad, 0x62, 0xd6, 0x72, 0x78, 0x27, 0x45, 0xa1, 0x01, 0x96, 0xae, 0x63, 0xcc, 0x06, 0x96, 0x43,
	0x03, 0x44, 0x38, 0xa1, 0x81, 0xbc, 0xd0, 0x10, 0xb5, 0xea, 0xf6, 0x66, 0xf3, 0xc1, 0xdd, 0xcd,
	0xa3, 0x44, 0xd9, 0xc9, 0x85, 0xed, 0xf9, 0xdb, 0x1f, 0x2f, 0x04, 0xb3, 0x76, 0x3d, 0x81, 0xc2,
	0x53, 0xb0, 0xdc, 0xc7, 0x11, 0x27, 0x81, 0xfb, 0x87, 0x67, 0x29, 0xf5, 0x7c, 0x39, 0xc3, 0xf3,
	0x34, 0xd3, 0x4e, 0xbb, 0xd6, 0xfb, 0x53, 0x38, 0x34, 0xc6, 0xbe, 0x17, 0x0c, 0x5f, 0xc7, 0x38,
	0x70, 0x06, 0x72, 0xb9, 0x21, 0x6a, 0xb5, 0xbf, 0xf9, 0x76, 0x73, 0x69, 0xe1, 0x58, 0x20, 0xaa,
	0x03, 0x6a, 0x93, 0x17, 0xc1, 0x1d, 0x50, 0x8e, 0xb8, 0x7d, 0x85, 0x59, 0x94, 0xa6, 0x5f, 0xdd,
	0xd6, 0xfe, 0x99, 0xc2, 0x71, 0xa6, 0xdf, 0x13, 0xcc, 0xbc, 0xb5, 0x5d, 0x05, 0x95, 0xe2, 0x72,
	0xf5, 0x9b, 0x08, 0xea, 0xd3, 0x37, 0xc2, 0x7d, 0x50, 0x09, 0x31, 0x0b, 0x31, 0x8f, 0x6d, 0x6f,
	0x34, 0xe9, 0xf5, 0x13, 0xb2, 0x31, 0xf2, 0x9e, 0x3d, 0xc1, 0x1c, 0x1b, 0xc0, 0x2e, 0x28, 0x7b,
	0xc4, 0x27, 0x1c, 0xa3, 0xf4, 0xf3, 0xa8, 0x6e, 0x6f, 0x3d, 0xc1, 0x6b, 0x3f, 0xeb, 0x48, 0xf6,
	0x1e, 0x35, 0x4f, 0xee, 0xbd, 0x0e, 0x56, 0x67, 0x1e, 0xaa, 0x6e, 0x80, 0xff, 0x1f, 0xdd, 0x4b,
	0x3d, 0x03, 0xeb, 0x8f, 0x0c, 0x82, 0x1b, 0xa0, 0x12, 0xc4, 0xbe, 0x15, 0x07, 0x84, 0x67, 0xe9,
	0xce, 0x99, 0x8b, 0x41, 0xec, 0x9f, 0x24, 0x35, 0xdc, 0x04, 0xff, 0x5d, 0x10, 0xcf, 0xc3, 0x68,
	0xc4, 0x4b, 0x29, 0x5f, 0xcd, 0xb0, 0x54, 0xb2, 0x45, 0x8b, 0x1c, 0x8b, 0x7f, 0x10, 0x6e, 0x82,
	0xe7, 0xa7, 0xfa, 0xf1, 0xa7, 0xde, 0xc1, 0xae, 0xd5, 0x35, 0xf5, 0xa3, 0x13, 0xfd, 0xa0, 0x73,
	0x66, 0x9d, 0x1c, 0x1c, 0x1b, 0x7a, 0xa7, 0xd7, 0xed, 0xe9, 0x3b, 0x75, 0x01, 0x6e, 0x80, 0xf5,
	0x87, 0x92, 0xf6, 0xfe, 0x61, 0xe7, 0x63, 0x5d, 0x9c, 0x4d, 0xea, 0xc6, 0x61, 0x67, 0xaf, 0x2e,
	0xb5, 0x8f, 0x6e, 0xef, 0x15, 0xf1, 0xee, 0x5e, 0x11, 0x7f, 0xde, 0x2b, 0xe2, 0xd7, 0xa1, 0x22,
	0xdc, 0x0d, 0x15, 0xe1, 0xfb, 0x50, 0x11, 0x3e, 0xbf, 0x77, 0x09, 0xbf, 0x8c, 0xcf, 0x9b, 0x0e,
	0xf5, 0x5b, 0x68, 0xe0, 0xe3, 0x20, 0x22, 0x34, 0xb8, 0x19, 0x7c, 0x19, 0x17, 0x6f, 0x18, 0xba,
	0x6a, 0xdd, 0xb4, 0xc6, 0x2f, 0x0a, 0x1f, 0x84, 0x38, 0x3a, 0x2f, 0xa5, 0x2f, 0xc5, 0xdb, 0xdf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x48, 0x52, 0x51, 0x56, 0x6b, 0x04, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DistrEpochIdentifier) > 0 {
		i -= len(m.DistrEpochIdentifier)
		copy(dAtA[i:], m.DistrEpochIdentifier)
		i = encodeVarintGauge(dAtA, i, uint64(len(m.DistrEpochIdentifier)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Gauge) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Gauge) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Gauge) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VestingFrequency != 0 {
		i = encodeVarintGauge(dAtA, i, uint64(m.VestingFrequency))
		i--
		dAtA[i] = 0x38
	}
	{
		size, err := m.VestingCondition.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGauge(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.QueryCondition.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGauge(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.ApprovedDenoms) > 0 {
		for iNdEx := len(m.ApprovedDenoms) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ApprovedDenoms[iNdEx])
			copy(dAtA[i:], m.ApprovedDenoms[iNdEx])
			i = encodeVarintGauge(dAtA, i, uint64(len(m.ApprovedDenoms[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintGauge(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintGauge(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryCondition) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCondition) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCondition) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Condition != nil {
		{
			size := m.Condition.Size()
			i -= size
			if _, err := m.Condition.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryCondition_Stakers) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCondition_Stakers) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Stakers != nil {
		{
			size, err := m.Stakers.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGauge(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *VestingCondition) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VestingCondition) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VestingCondition) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Condition != nil {
		{
			size := m.Condition.Size()
			i -= size
			if _, err := m.Condition.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *VestingCondition_Perpetual) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VestingCondition_Perpetual) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Perpetual != nil {
		{
			size, err := m.Perpetual.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGauge(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *VestingCondition_Limited) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VestingCondition_Limited) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Limited != nil {
		{
			size, err := m.Limited.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGauge(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *QueryConditionStakers) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryConditionStakers) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryConditionStakers) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *VestingConditionPerpetual) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VestingConditionPerpetual) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VestingConditionPerpetual) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *VestingConditionLimited) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VestingConditionLimited) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VestingConditionLimited) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FilledUnits != 0 {
		i = encodeVarintGauge(dAtA, i, uint64(m.FilledUnits))
		i--
		dAtA[i] = 0x10
	}
	if m.NumUnits != 0 {
		i = encodeVarintGauge(dAtA, i, uint64(m.NumUnits))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGauge(dAtA []byte, offset int, v uint64) int {
	offset -= sovGauge(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DistrEpochIdentifier)
	if l > 0 {
		n += 1 + l + sovGauge(uint64(l))
	}
	return n
}

func (m *Gauge) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovGauge(uint64(m.Id))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovGauge(uint64(l))
	}
	if m.Active {
		n += 2
	}
	if len(m.ApprovedDenoms) > 0 {
		for _, s := range m.ApprovedDenoms {
			l = len(s)
			n += 1 + l + sovGauge(uint64(l))
		}
	}
	l = m.QueryCondition.Size()
	n += 1 + l + sovGauge(uint64(l))
	l = m.VestingCondition.Size()
	n += 1 + l + sovGauge(uint64(l))
	if m.VestingFrequency != 0 {
		n += 1 + sovGauge(uint64(m.VestingFrequency))
	}
	return n
}

func (m *QueryCondition) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Condition != nil {
		n += m.Condition.Size()
	}
	return n
}

func (m *QueryCondition_Stakers) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Stakers != nil {
		l = m.Stakers.Size()
		n += 1 + l + sovGauge(uint64(l))
	}
	return n
}
func (m *VestingCondition) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Condition != nil {
		n += m.Condition.Size()
	}
	return n
}

func (m *VestingCondition_Perpetual) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Perpetual != nil {
		l = m.Perpetual.Size()
		n += 1 + l + sovGauge(uint64(l))
	}
	return n
}
func (m *VestingCondition_Limited) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Limited != nil {
		l = m.Limited.Size()
		n += 1 + l + sovGauge(uint64(l))
	}
	return n
}
func (m *QueryConditionStakers) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *VestingConditionPerpetual) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *VestingConditionLimited) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NumUnits != 0 {
		n += 1 + sovGauge(uint64(m.NumUnits))
	}
	if m.FilledUnits != 0 {
		n += 1 + sovGauge(uint64(m.FilledUnits))
	}
	return n
}

func sovGauge(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGauge(x uint64) (n int) {
	return sovGauge(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGauge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistrEpochIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGauge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGauge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGauge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DistrEpochIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGauge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGauge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Gauge) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGauge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Gauge: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Gauge: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGauge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGauge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGauge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGauge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGauge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApprovedDenoms", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGauge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGauge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGauge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApprovedDenoms = append(m.ApprovedDenoms, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueryCondition", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGauge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGauge
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGauge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.QueryCondition.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingCondition", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGauge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGauge
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGauge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VestingCondition.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingFrequency", wireType)
			}
			m.VestingFrequency = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGauge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VestingFrequency |= VestingFrequency(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGauge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGauge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCondition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGauge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCondition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCondition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stakers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGauge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGauge
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGauge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &QueryConditionStakers{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Condition = &QueryCondition_Stakers{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGauge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGauge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VestingCondition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGauge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VestingCondition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VestingCondition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Perpetual", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGauge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGauge
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGauge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &VestingConditionPerpetual{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Condition = &VestingCondition_Perpetual{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limited", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGauge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGauge
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGauge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &VestingConditionLimited{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Condition = &VestingCondition_Limited{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGauge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGauge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryConditionStakers) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGauge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryConditionStakers: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryConditionStakers: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipGauge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGauge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VestingConditionPerpetual) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGauge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VestingConditionPerpetual: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VestingConditionPerpetual: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipGauge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGauge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VestingConditionLimited) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGauge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VestingConditionLimited: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VestingConditionLimited: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumUnits", wireType)
			}
			m.NumUnits = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGauge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumUnits |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FilledUnits", wireType)
			}
			m.FilledUnits = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGauge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FilledUnits |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGauge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGauge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGauge(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGauge
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGauge
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGauge
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGauge
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGauge
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGauge
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGauge        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGauge          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGauge = fmt.Errorf("proto: unexpected end of group")
)
