// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: staking/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	types "github.com/cosmos/cosmos-sdk/x/staking/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgCreateValidatorERC20 defines a SDK message for creating a new validator.
type MsgCreateValidatorERC20 struct {
	Value types.MsgCreateValidator `protobuf:"bytes,1,opt,name=value,proto3" json:"value"`
}

func (m *MsgCreateValidatorERC20) Reset()         { *m = MsgCreateValidatorERC20{} }
func (m *MsgCreateValidatorERC20) String() string { return proto.CompactTextString(m) }
func (*MsgCreateValidatorERC20) ProtoMessage()    {}
func (*MsgCreateValidatorERC20) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ec9a3a1971dd6a6, []int{0}
}
func (m *MsgCreateValidatorERC20) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateValidatorERC20) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateValidatorERC20.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateValidatorERC20) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateValidatorERC20.Merge(m, src)
}
func (m *MsgCreateValidatorERC20) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateValidatorERC20) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateValidatorERC20.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateValidatorERC20 proto.InternalMessageInfo

func (m *MsgCreateValidatorERC20) GetValue() types.MsgCreateValidator {
	if m != nil {
		return m.Value
	}
	return types.MsgCreateValidator{}
}

// MsgDelegateERC20 defines a SDK message for performing a delegation of coins
// from a delegator to a validator.
type MsgDelegateERC20 struct {
	Value types.MsgDelegate `protobuf:"bytes,1,opt,name=value,proto3" json:"value"`
}

func (m *MsgDelegateERC20) Reset()         { *m = MsgDelegateERC20{} }
func (m *MsgDelegateERC20) String() string { return proto.CompactTextString(m) }
func (*MsgDelegateERC20) ProtoMessage()    {}
func (*MsgDelegateERC20) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ec9a3a1971dd6a6, []int{1}
}
func (m *MsgDelegateERC20) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDelegateERC20) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDelegateERC20.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDelegateERC20) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDelegateERC20.Merge(m, src)
}
func (m *MsgDelegateERC20) XXX_Size() int {
	return m.Size()
}
func (m *MsgDelegateERC20) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDelegateERC20.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDelegateERC20 proto.InternalMessageInfo

func (m *MsgDelegateERC20) GetValue() types.MsgDelegate {
	if m != nil {
		return m.Value
	}
	return types.MsgDelegate{}
}

func init() {
	proto.RegisterType((*MsgCreateValidatorERC20)(nil), "rollapp.staking.MsgCreateValidatorERC20")
	proto.RegisterType((*MsgDelegateERC20)(nil), "rollapp.staking.MsgDelegateERC20")
}

func init() { proto.RegisterFile("staking/tx.proto", fileDescriptor_5ec9a3a1971dd6a6) }

var fileDescriptor_5ec9a3a1971dd6a6 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x13, 0xfc, 0x73, 0x88, 0x88, 0x25, 0x14, 0xaa, 0x39, 0x6c, 0xb5, 0x5e, 0x8a, 0xe2,
	0xae, 0x8d, 0x78, 0x16, 0x5a, 0xf5, 0x56, 0x84, 0x0a, 0x1e, 0xbc, 0xc8, 0xa6, 0x1d, 0xd7, 0xd0,
	0x24, 0x13, 0xb2, 0xdb, 0xd2, 0xf8, 0x14, 0x3e, 0x56, 0x8f, 0x3d, 0x7a, 0x10, 0x91, 0xf6, 0x45,
	0xa4, 0xcd, 0x46, 0x89, 0x56, 0xe9, 0x29, 0x33, 0xf9, 0x66, 0x7e, 0x33, 0xdf, 0x8e, 0x55, 0x92,
	0x8a, 0xf7, 0xfd, 0x48, 0x30, 0x35, 0xa2, 0x71, 0x82, 0x0a, 0xed, 0x9d, 0x04, 0x83, 0x80, 0xc7,
	0x31, 0xd5, 0x8a, 0x53, 0xe9, 0xa2, 0x0c, 0x51, 0xb2, 0x50, 0x0a, 0x36, 0x6c, 0xcc, 0x3f, 0x59,
	0xa5, 0x53, 0x16, 0x28, 0x70, 0x11, 0xb2, 0x79, 0xa4, 0xff, 0xee, 0x09, 0x44, 0x11, 0x00, 0x5b,
	0x64, 0xde, 0xe0, 0x91, 0xf1, 0x28, 0xd5, 0x12, 0xd1, 0x24, 0x8f, 0x4b, 0x60, 0xc3, 0x86, 0x07,
	0x8a, 0x37, 0x58, 0x17, 0xfd, 0x48, 0xeb, 0x55, 0xad, 0xe7, 0x3b, 0xe5, 0x25, 0xf9, 0x6e, 0x35,
	0x6e, 0x55, 0xda, 0x52, 0xb4, 0x12, 0xe0, 0x0a, 0xee, 0x78, 0xe0, 0xf7, 0xb8, 0xc2, 0xe4, 0xaa,
	0xd3, 0x72, 0x4f, 0xed, 0x6b, 0x6b, 0x63, 0xc8, 0x83, 0x01, 0xec, 0x9a, 0xfb, 0x66, 0x7d, 0xcb,
	0x3d, 0xa2, 0x19, 0x2b, 0x77, 0x41, 0x35, 0x8b, 0xfe, 0xee, 0x6f, 0xae, 0x8f, 0xdf, 0xab, 0x46,
	0x27, 0x6b, 0xaf, 0xdd, 0x5a, 0xa5, 0xb6, 0x14, 0x97, 0x10, 0x80, 0xe0, 0x0a, 0x32, 0xf6, 0x45,
	0x91, 0x7d, 0xf8, 0x0f, 0x3b, 0x6f, 0x2c, 0x40, 0xdd, 0x37, 0xd3, 0x5a, 0x6b, 0x4b, 0x61, 0x2b,
	0xab, 0xbc, 0x74, 0xf9, 0x3a, 0xfd, 0xf1, 0xe8, 0xf4, 0x0f, 0x9b, 0x8e, 0xbb, 0xba, 0xaf, 0x0e,
	0xc8, 0x18, 0x23, 0x09, 0xf6, 0x83, 0xb5, 0x5d, 0xf4, 0x73, 0xb0, 0x6c, 0x5c, 0xa1, 0xc4, 0x39,
	0x5e, 0xc1, 0x63, 0x3e, 0xa0, 0x79, 0x33, 0x9e, 0x12, 0x73, 0x32, 0x25, 0xe6, 0xc7, 0x94, 0x98,
	0x2f, 0x33, 0x62, 0x4c, 0x66, 0xc4, 0x78, 0x9d, 0x11, 0xe3, 0xfe, 0x5c, 0xf8, 0xea, 0x69, 0xe0,
	0xd1, 0x2e, 0x86, 0xac, 0x97, 0x86, 0x10, 0x49, 0x1f, 0xa3, 0x51, 0xfa, 0xfc, 0x9d, 0x9c, 0x24,
	0xbd, 0x3e, 0x1b, 0x7d, 0x9d, 0x5c, 0xa5, 0x31, 0x48, 0x6f, 0x73, 0x71, 0xee, 0xb3, 0xcf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xca, 0x76, 0x44, 0x5f, 0x9e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// CreateValidator defines a method for creating a new validator.
	CreateValidatorERC20(ctx context.Context, in *MsgCreateValidatorERC20, opts ...grpc.CallOption) (*types.MsgCreateValidatorResponse, error)
	// Delegate defines a method for performing a delegation of coins
	// from a delegator to a validator.
	DelegateERC20(ctx context.Context, in *MsgDelegateERC20, opts ...grpc.CallOption) (*types.MsgDelegateResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateValidatorERC20(ctx context.Context, in *MsgCreateValidatorERC20, opts ...grpc.CallOption) (*types.MsgCreateValidatorResponse, error) {
	out := new(types.MsgCreateValidatorResponse)
	err := c.cc.Invoke(ctx, "/rollapp.staking.Msg/CreateValidatorERC20", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DelegateERC20(ctx context.Context, in *MsgDelegateERC20, opts ...grpc.CallOption) (*types.MsgDelegateResponse, error) {
	out := new(types.MsgDelegateResponse)
	err := c.cc.Invoke(ctx, "/rollapp.staking.Msg/DelegateERC20", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// CreateValidator defines a method for creating a new validator.
	CreateValidatorERC20(context.Context, *MsgCreateValidatorERC20) (*types.MsgCreateValidatorResponse, error)
	// Delegate defines a method for performing a delegation of coins
	// from a delegator to a validator.
	DelegateERC20(context.Context, *MsgDelegateERC20) (*types.MsgDelegateResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateValidatorERC20(ctx context.Context, req *MsgCreateValidatorERC20) (*types.MsgCreateValidatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateValidatorERC20 not implemented")
}
func (*UnimplementedMsgServer) DelegateERC20(ctx context.Context, req *MsgDelegateERC20) (*types.MsgDelegateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelegateERC20 not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateValidatorERC20_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateValidatorERC20)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateValidatorERC20(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rollapp.staking.Msg/CreateValidatorERC20",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateValidatorERC20(ctx, req.(*MsgCreateValidatorERC20))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DelegateERC20_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDelegateERC20)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DelegateERC20(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rollapp.staking.Msg/DelegateERC20",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DelegateERC20(ctx, req.(*MsgDelegateERC20))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rollapp.staking.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateValidatorERC20",
			Handler:    _Msg_CreateValidatorERC20_Handler,
		},
		{
			MethodName: "DelegateERC20",
			Handler:    _Msg_DelegateERC20_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "staking/tx.proto",
}

func (m *MsgCreateValidatorERC20) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateValidatorERC20) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateValidatorERC20) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Value.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgDelegateERC20) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDelegateERC20) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDelegateERC20) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Value.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateValidatorERC20) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Value.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgDelegateERC20) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Value.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateValidatorERC20) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateValidatorERC20: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateValidatorERC20: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Value.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDelegateERC20) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDelegateERC20: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDelegateERC20: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Value.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
