#SETTLEMENT CONFIG
KEY_NAME_GENESIS=${KEY_NAME_GENESIS:-"local-user"}
KEY_NAME_DYM=${KEY_NAME_DYM:-"local-sequencer"}
KEYRING_PATH=${KEYRING_PATH:-"$HOME/.dymension"}
SETTLEMENT_EXECUTABLE=${SETTLEMENT_EXECUTABLE:-dymd}
SETTLEMENT_CHAIN_ID=${SETTLEMENT_CHAIN_ID:-"local-testnet"}
SETTLEMENT_RPC=${SETTLEMENT_RPC:-"127.0.0.1:36657"}


#TODO: make most params based on chain ID
#ROLLAPP CONFIG
KEY_NAME_ROLLAPP=${KEY_NAME_ROLLAPP:-"rol-user"}
EXECUTABLE=${EXECUTABLE:-rollappd}
CHAIN_ID=${CHAIN_ID:-rollapp}
CHAIN_DIR=${CHAIN_DIR:-$HOME/.rollapp}
ROLLAPP_ID=${ROLLAPP_ID:-rollapp}
MONIKER=${MONIKER:-rollapp-sequencer}
NAMESPACE_ID=${NAMESPACE_ID:-000000000000FFFF}
RPC_PORT=${RPC_PORT:-"0.0.0.0:26667"}
P2P_PORT=${P2P_PORT:-"0.0.0.0:26668"}
GRPC_PORT=${GRPC_PORT:-"0.0.0.0:9080"}
GRPC_WEB_PORT=${GRPC_WEB_PORT:-"0.0.0.0:9081"}
API_ADDRESS=${API_ADDRESS:-"0.0.0.0:1417"}


#IBC CONFIG
RELAYER_KEY_FOR_ROLLAP=${RELAYER_KEY_FOR_ROLLAP:-"relayer-rollapp-key"}
RELAYER_KEY_FOR_HUB=${RELAYER_KEY_FOR_HUB:-"relayer-hub-key"}
RELAYER_PATH=${RELAYER_PATH:-"hub-rollapp"}
ROLLAPP_CHANNEL_NAME=${ROLLAPP_CHANNEL_NAME:-"channel-0"}
HUB_CHANNEL_NAME=${HUB_ROLLAPP_CHANNEL_NAME:-"channel-0"}